# Generated by Django 6.0.3 on 2026-04-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_is_paid_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
