# Generated by Django 6.0.3 on 2026-06-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_banner_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional sale price. Must be lower than the original price. Leave empty for no discount.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, choices=[('', '— No Tag —'), ('best_selling', 'Best Selling'), ('new_arrival', 'New Arrival'), ('pre_order', 'Pre Order')], default='', help_text='Optional badge shown on the product card (e.g. "Best Selling").', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Original price. If a discount price is also set, this will show as a crossed-out price.', max_digits=10),
        ),
    ]
